# Generated by Django 4.0.6 on 2022-08-06 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_spending_fk_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='main_ua',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=9854544344, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=957343456, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
