# Generated by Django 4.0.6 on 2022-07-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_spending_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
