# Generated by Django 4.0.6 on 2022-07-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_alter_spending_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spending',
            options={'ordering': ('-date_time_created',)},
        ),
    ]
